name: Integracao Jira CI

on:
  push:
    branches:
      - testes
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4. Instalar o xmllint
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      # 5. Rodar testes
      - name: Run tests
        id: pytest
        run: |
          pytest --junitxml=results.xml
        continue-on-error: true

      # 6. Contar falhas no XML usando xmllint e Criar uma issue de bug no Jira
      - name: Extrair resultado do teste e Criar issue no Jira
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          # Verificar se o arquivo XML existe
          if [ -s "results.xml" ]; then
            echo "O arquivo do Resultado Dos Testes foi encontrado. Extraindo Os resultados..."
            
            # Contar o número de falhas
            FAILED_TESTS=$(xmllint --xpath "count(//failure)" results.xml | tr -d '[:space:]')

            if [ "$FAILED_TESTS" -gt 0 ]; then
              # Extrair as mensagens de falha
              FAILURE_MESSAGES=$(xmllint --xpath "//failure/@message" results.xml)
              # Exibir no log
              echo "Failed tests: $FAILED_TESTS"
              echo "Failure messages: $FAILURE_MESSAGES"
              curl -X POST \
                -u "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
                -H "Content-Type: application/json" \
                -d '{
                  "fields": {
                    "project": {
                      "key": "T1"
                    },
                    "summary": "Test failures detected in CI pipeline",
                    "description": "Testes falhados: '"$FAILED_TESTS"'.\nHash Do Commit:\n- Commit: '"${{ github.sha }}"'\n- Autor: '"${{ github.actor }}"'\n- Mesagem: '"${{ github.event.head_commit.message }}"'",
                    "issuetype": {
                      "name": "Bug"
                    }
                  }
                }' $JIRA_BASE_URL/rest/api/2/issue/
            else
                echo "Nao foi encontrado falha nos testes. Todos os testes passaram."
            fi        
          else
            echo "No test results file found. All tests are passing, and no errors were reported."
          fi