name: Python CI with Jira Integration

on:
  push:
    branches:
      - testes
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4. Instalar o xmllint
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      # 5. Rodar testes
      - name: Run tests
        id: pytest
        run: |
          pytest --junitxml=results.xml
        continue-on-error: true

      # 6. Contar falhas no XML usando xmllint
      - name: Extract test results and create Jira issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          # Contar o número de falhas
          FAILED_TESTS=$(xmllint --xpath "count(//failure)" results.xml | tr -d '[:space:]')

          # Extrair as mensagens de falha
          FAILURE_MESSAGES=$(xmllint --xpath "//failure/@message" results.xml)

          # Substituir quebras de linha por espaço e escapar aspas
          FAILURE_MESSAGES=$(echo "$FAILURE_MESSAGES" | sed 's/"/\\"/g' | tr '\n' ' ')

          # Exibir no log
          echo "Failed tests: $FAILED_TESTS"
          echo "Failure messages: $FAILURE_MESSAGES"

          if [ "$FAILED_TESTS" -gt 0 ]; then
            AUTH=$(echo -n "${JIRA_EMAIL}:${JIRA_API_TOKEN}" | base64)
            curl -X POST \
              -u "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{
                "fields": {
                  "project": {
                    "key": "T1" 
                  },
                  "summary": "Test failures detected in CI pipeline",
                  "description": "Failed tests: $FAILED_TESTS.\nFailure details: $FAILURE_MESSAGES\nCommit Information:\n- Commit: ${{ github.sha }}\n- Author: ${{ github.actor }}\n- Message: ${{ github.event.head_commit.message }}",
                  "issuetype": {
                    "name": "Bug"
                  }
              }' $JIRA_BASE_URL/rest/api/2/issue/
          fi